// AUTO-GENERATED from contracts/src/AetherGovernance.sol — DO NOT EDIT
// Generated by scripts/regen-frontend-abi.js
// Solidity 0.8.26, OpenZeppelin Contracts v5
export const AetherGovernanceABI = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_ringAddress",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AccessControlBadConfirmation",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "neededRole",
        "type": "bytes32"
      }
    ],
    "name": "AccessControlUnauthorizedAccount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyExecuted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyFinalized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadySigned",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyVoted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmptyIpfs",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmptyTitle",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ImpeachmentTargetInvalid",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidChamberWeights",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidVoteOption",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotChamberMember",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotDrafting",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotEligibleSigner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotImpeachmentType",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotInVotingPeriod",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotPendingMultisig",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotRingBearer",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "NotSafeWallet",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      }
    ],
    "name": "ParamSelectorNotWhitelisted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ProposalNotQueued",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SafeWalletNotSet",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "current",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "required",
        "type": "uint256"
      }
    ],
    "name": "SignaturesNotMet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TimelockNotElapsed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TreasuryTargetZero",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      }
    ],
    "name": "UnknownTier",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VotingNotEnded",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "ImpeachmentApprovedByMultisig",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "ImpeachmentRejectedByMultisig",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "current",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "required",
        "type": "uint256"
      }
    ],
    "name": "ImpeachmentSignatureAdded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "ImpeachmentSubmittedToMultisig",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "ProposalCanceled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "proposer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "enum AetherGovernance.ProposalType",
        "name": "pType",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "title",
        "type": "string"
      }
    ],
    "name": "ProposalCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bytes",
        "name": "returnData",
        "type": "bytes"
      }
    ],
    "name": "ProposalExecuted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "passed",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "enum AetherGovernance.ChamberStance",
        "name": "consensus",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "forWeighted",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "againstWeighted",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "memberQuorumMet",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "memberVeto",
        "type": "bool"
      }
    ],
    "name": "ProposalFinalized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "executeAfter",
        "type": "uint256"
      }
    ],
    "name": "ProposalQueued",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "previousAdminRole",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "newAdminRole",
        "type": "bytes32"
      }
    ],
    "name": "RoleAdminChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "RoleGranted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "RoleRevoked",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "oldSafe",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newSafe",
        "type": "address"
      }
    ],
    "name": "SafeWalletUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "voter",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "enum AetherGovernance.VoteOption",
        "name": "option",
        "type": "uint8"
      }
    ],
    "name": "VoteCast",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "ADMIN_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "BPS_DENOMINATOR",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "CHAMBER_WEIGHT_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "DEFAULT_ADMIN_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "IMPEACHMENT_QUORUM_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "IMPEACHMENT_SIGNATURES_REQUIRED",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "IMPEACHMENT_VETO_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MEMBER_QUORUM_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MEMBER_VETO_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MEMBER_WEIGHT_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "PASS_THRESHOLD_BPS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "PROPOSER_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "approveImpeachmentByMultisig",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "cancelProposal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      },
      {
        "internalType": "enum AetherGovernance.VoteOption",
        "name": "option",
        "type": "uint8"
      }
    ],
    "name": "castVote",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "title",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "ipfsHash",
        "type": "string"
      }
    ],
    "name": "createImpeachmentProposal",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "enum AetherGovernance.ProposalType",
        "name": "pType",
        "type": "uint8"
      },
      {
        "internalType": "string",
        "name": "title",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "ipfsHash",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "calldataPayload",
        "type": "bytes"
      }
    ],
    "name": "createProposal",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "executeProposal",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "finalizeProposal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "getNormalVoteCounts",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "parliamentFor",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "parliamentAgainst",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "federationFor",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "federationAgainst",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "senateFor",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "senateAgainst",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "memberFor",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "memberAgainst",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "memberAbstain",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "memberTotalSnapshot",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalForWeighted",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalAgainstWeighted",
        "type": "uint256"
      },
      {
        "internalType": "enum AetherGovernance.ChamberStance",
        "name": "chamberConsensus",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "memberQuorumMet",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "memberVetoTriggered",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "getProposal",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "proposer",
        "type": "address"
      },
      {
        "internalType": "enum AetherGovernance.ProposalType",
        "name": "pType",
        "type": "uint8"
      },
      {
        "internalType": "string",
        "name": "title",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "ipfsHash",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "votingStartAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "votingEndAt",
        "type": "uint256"
      },
      {
        "internalType": "enum AetherGovernance.ProposalStatus",
        "name": "status",
        "type": "uint8"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "executeAfter",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "isFinalized",
        "type": "bool"
      },
      {
        "internalType": "address",
        "name": "impeachedTarget",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "currentSignatures",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "requiredSignatures",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      }
    ],
    "name": "getRoleAdmin",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "voter",
        "type": "address"
      }
    ],
    "name": "getVoterVote",
    "outputs": [
      {
        "internalType": "enum AetherGovernance.VoteOption",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "grantProposerRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "grantRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "hasRole",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      }
    ],
    "name": "hasSigned",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "name": "internalWeight",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "proposalCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "proposals",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "proposer",
        "type": "address"
      },
      {
        "internalType": "enum AetherGovernance.ProposalType",
        "name": "pType",
        "type": "uint8"
      },
      {
        "internalType": "string",
        "name": "title",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "ipfsHash",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "createdAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "votingStartAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "votingEndAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "parliamentFor",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "parliamentAgainst",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "federationFor",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "federationAgainst",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "senateFor",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "senateAgainst",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "memberFor",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "memberAgainst",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "memberAbstain",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "memberTotalSnapshot",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalForWeighted",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalAgainstWeighted",
        "type": "uint256"
      },
      {
        "internalType": "enum AetherGovernance.ChamberStance",
        "name": "chamberConsensus",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "memberQuorumMet",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "memberVetoTriggered",
        "type": "bool"
      },
      {
        "internalType": "enum AetherGovernance.ProposalStatus",
        "name": "status",
        "type": "uint8"
      },
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "calldataPayload",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "queuedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "executeAfter",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "isFinalized",
        "type": "bool"
      },
      {
        "internalType": "address",
        "name": "impeachedTarget",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "requiredSignatures",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "currentSignatures",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "rejectImpeachmentByMultisig",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "callerConfirmation",
        "type": "address"
      }
    ],
    "name": "renounceRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "revokeProposerRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "revokeRole",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "ringContract",
    "outputs": [
      {
        "internalType": "contract IAetherRing",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "safeWallet",
    "outputs": [
      {
        "internalType": "contract ISafe",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_parliament",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_federation",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_senate",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_member",
        "type": "uint256"
      }
    ],
    "name": "setChamberWeights",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "weight",
        "type": "uint256"
      }
    ],
    "name": "setInternalWeight",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_ringAddress",
        "type": "address"
      }
    ],
    "name": "setRingContract",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_safe",
        "type": "address"
      }
    ],
    "name": "setSafeWallet",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_signal",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_treasury",
        "type": "uint256"
      }
    ],
    "name": "setTimelocks",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_period",
        "type": "uint256"
      }
    ],
    "name": "setVotingPeriod",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "signImpeachment",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "simulateFinalize",
    "outputs": [
      {
        "internalType": "bool",
        "name": "wouldPass",
        "type": "bool"
      },
      {
        "internalType": "enum AetherGovernance.ChamberStance",
        "name": "consensus",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "quorumMet",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "vetoTriggered",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "totalForWeighted",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalAgainstWeighted",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "simulateImpeachmentResult",
    "outputs": [
      {
        "internalType": "bool",
        "name": "wouldPass",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "quorumMet",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "vetoTriggered",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "name": "supportsInterface",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "timelockImpeachment",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "timelockSignal",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "timelockTreasury",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "votes",
    "outputs": [
      {
        "internalType": "enum AetherGovernance.VoteOption",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "votingPeriod",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
